[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Iosevka"
style = "Bold"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"

[window.padding]
x = 15
y = 15
