[tools]
"cargo:sccache" = "0.15.0"
node = "22"
python = "3.13"

[settings]
trusted_config_paths = [
  "~/Developer/Tractorbeam",
  "~/Developer/wadefletch",
]
activate_aggressive = true
idiomatic_version_file_enable_tools = ["node", "python"]
lockfile = true
minimum_release_age = "7d"

[settings.python]
compile = false
